/*
 xxx
 */
package formularios;

import static formularios.acceso.codusu;
import static formularios.acceso.nivel;
import static formularios.acceso.usunombre;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import prg.VentanaBuscar;
import prg.conex;

/**
 *
 * @author utic
 */
public class Compra extends javax.swing.JDialog {

    conex con; //llamar al metodo conexión
    ResultSet rs, rs1; //llamar al metodo de resultados
    javax.swing.table.DefaultTableModel cursor, cur_cab, cur_det;//crear cursor

    int cantstock;
    int r, r1, rt = 0;
    int total = 0;
    int accion = 0;

    DecimalFormat formateador = new DecimalFormat("###,###,###");

    public Compra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);

        con = new conex(); //Instanciar la coenxion
        con.conectar(); //Utilizar el metodo para conectar
        fecha();
        hora();
        llenar_combo_depo("0");
        this.user.setText(acceso.usunombre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelMetric1 = new org.edisoncor.gui.label.LabelMetric();
        jScrollPane1 = new javax.swing.JScrollPane();
        grilla = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        labelMetric5 = new org.edisoncor.gui.label.LabelMetric();
        cod = new org.edisoncor.gui.textField.TextFieldRectBackground();
        labelMetric2 = new org.edisoncor.gui.label.LabelMetric();
        user = new org.edisoncor.gui.textField.TextFieldRectBackground();
        labelMetric3 = new org.edisoncor.gui.label.LabelMetric();
        fecha = new org.edisoncor.gui.textField.TextFieldRectBackground();
        labelMetric4 = new org.edisoncor.gui.label.LabelMetric();
        hora = new org.edisoncor.gui.textField.TextFieldRectBackground();
        jPanel3 = new javax.swing.JPanel();
        labelMetric6 = new org.edisoncor.gui.label.LabelMetric();
        cod_prov = new org.edisoncor.gui.textField.TextFieldRectBackground();
        proveedor = new org.edisoncor.gui.textField.TextFieldRectBackground();
        labelMetric7 = new org.edisoncor.gui.label.LabelMetric();
        nro_fac = new org.edisoncor.gui.textField.TextFieldRectBackground();
        labelMetric11 = new org.edisoncor.gui.label.LabelMetric();
        cbo_deposito = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        labelMetric8 = new org.edisoncor.gui.label.LabelMetric();
        txt_cod_produc = new org.edisoncor.gui.textField.TextFieldRectBackground();
        txt_produc = new org.edisoncor.gui.textField.TextFieldRectBackground();
        labelMetric9 = new org.edisoncor.gui.label.LabelMetric();
        txt_precio = new org.edisoncor.gui.textField.TextFieldRectBackground();
        labelMetric10 = new org.edisoncor.gui.label.LabelMetric();
        txt_cantidad = new org.edisoncor.gui.textField.TextFieldRectBackground();
        jButton1 = new javax.swing.JButton();
        btnagregar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        txt_total = new org.edisoncor.gui.textField.TextFieldRectBackground();
        labelMetric12 = new org.edisoncor.gui.label.LabelMetric();
        btncancelar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        labelMetric13 = new org.edisoncor.gui.label.LabelMetric();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(185, 176, 168));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelMetric1.setBackground(new java.awt.Color(0, 0, 0));
        labelMetric1.setForeground(new java.awt.Color(0, 0, 0));
        labelMetric1.setText("Compra de Mercadería");
        labelMetric1.setColorDeSombra(new java.awt.Color(255, 255, 255));
        labelMetric1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Producto", "Precio", "Cantidad", "cod_deposito"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grilla.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(grilla);
        if (grilla.getColumnModel().getColumnCount() > 0) {
            grilla.getColumnModel().getColumn(0).setResizable(false);
            grilla.getColumnModel().getColumn(1).setResizable(false);
            grilla.getColumnModel().getColumn(2).setResizable(false);
            grilla.getColumnModel().getColumn(3).setResizable(false);
            grilla.getColumnModel().getColumn(4).setMinWidth(0);
            grilla.getColumnModel().getColumn(4).setPreferredWidth(0);
            grilla.getColumnModel().getColumn(4).setMaxWidth(0);
        }

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setOpaque(false);

        labelMetric5.setBackground(new java.awt.Color(0, 0, 0));
        labelMetric5.setForeground(new java.awt.Color(0, 0, 0));
        labelMetric5.setText("Codigo:");
        labelMetric5.setColorDeSombra(new java.awt.Color(255, 255, 255));
        labelMetric5.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N

        cod.setEnabled(false);

        labelMetric2.setText("Usuario:");
        labelMetric2.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N

        user.setEnabled(false);
        user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userKeyPressed(evt);
            }
        });

        labelMetric3.setBackground(new java.awt.Color(0, 0, 0));
        labelMetric3.setForeground(new java.awt.Color(0, 0, 0));
        labelMetric3.setText("Fecha:");
        labelMetric3.setColorDeSombra(new java.awt.Color(255, 255, 255));
        labelMetric3.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N

        fecha.setEnabled(false);

        labelMetric4.setBackground(new java.awt.Color(0, 0, 0));
        labelMetric4.setForeground(new java.awt.Color(0, 0, 0));
        labelMetric4.setText("Hora:");
        labelMetric4.setColorDeSombra(new java.awt.Color(255, 255, 255));
        labelMetric4.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N

        hora.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMetric5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelMetric2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(labelMetric3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(labelMetric4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelMetric4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelMetric3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelMetric2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelMetric5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setOpaque(false);

        labelMetric6.setBackground(new java.awt.Color(0, 0, 0));
        labelMetric6.setForeground(new java.awt.Color(0, 0, 0));
        labelMetric6.setText("Proveedor");
        labelMetric6.setColorDeSombra(new java.awt.Color(255, 255, 255));
        labelMetric6.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N

        cod_prov.setEnabled(false);
        cod_prov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cod_provActionPerformed(evt);
            }
        });
        cod_prov.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cod_provKeyPressed(evt);
            }
        });

        proveedor.setEnabled(false);

        labelMetric7.setBackground(new java.awt.Color(0, 0, 0));
        labelMetric7.setForeground(new java.awt.Color(0, 0, 0));
        labelMetric7.setText("Nro Factura:");
        labelMetric7.setColorDeSombra(new java.awt.Color(255, 255, 255));
        labelMetric7.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N

        nro_fac.setEnabled(false);
        nro_fac.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nro_fac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nro_facActionPerformed(evt);
            }
        });

        labelMetric11.setBackground(new java.awt.Color(0, 0, 0));
        labelMetric11.setForeground(new java.awt.Color(0, 0, 0));
        labelMetric11.setText("Depósito:");
        labelMetric11.setColorDeSombra(new java.awt.Color(255, 255, 255));
        labelMetric11.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N

        cbo_deposito.setFont(new java.awt.Font("DejaVu Sans", 1, 16)); // NOI18N
        cbo_deposito.setEnabled(false);
        cbo_deposito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbo_depositoMouseClicked(evt);
            }
        });
        cbo_deposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_depositoActionPerformed(evt);
            }
        });
        cbo_deposito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbo_depositoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labelMetric6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cod_prov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelMetric7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nro_fac, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelMetric11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(cbo_deposito, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cod_prov, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nro_fac, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMetric6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMetric7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMetric11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbo_deposito, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setOpaque(false);

        labelMetric8.setBackground(new java.awt.Color(0, 0, 0));
        labelMetric8.setForeground(new java.awt.Color(0, 0, 0));
        labelMetric8.setText("Producto:");
        labelMetric8.setColorDeSombra(new java.awt.Color(255, 255, 255));
        labelMetric8.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N

        txt_cod_produc.setEnabled(false);
        txt_cod_produc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cod_producActionPerformed(evt);
            }
        });
        txt_cod_produc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cod_producKeyPressed(evt);
            }
        });

        txt_produc.setDescripcion("producto");
        txt_produc.setEnabled(false);
        txt_produc.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        labelMetric9.setBackground(new java.awt.Color(0, 0, 0));
        labelMetric9.setForeground(new java.awt.Color(0, 0, 0));
        labelMetric9.setText("Precio");
        labelMetric9.setColorDeSombra(new java.awt.Color(255, 255, 255));
        labelMetric9.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N

        txt_precio.setDescripcion("precio");
        txt_precio.setEnabled(false);
        txt_precio.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_precioActionPerformed(evt);
            }
        });

        labelMetric10.setBackground(new java.awt.Color(0, 0, 0));
        labelMetric10.setForeground(new java.awt.Color(0, 0, 0));
        labelMetric10.setText("Cantidad:");
        labelMetric10.setColorDeSombra(new java.awt.Color(255, 255, 255));
        labelMetric10.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N

        txt_cantidad.setDescripcion("cantidad");
        txt_cantidad.setEnabled(false);
        txt_cantidad.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cantidadActionPerformed(evt);
            }
        });
        txt_cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cantidadKeyPressed(evt);
            }
        });

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMetric8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_cod_produc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_produc, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(labelMetric9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(labelMetric10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_cod_produc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_produc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelMetric8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelMetric9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelMetric10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btnagregar.setText("Agregar");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        btnguardar.setText("Grabar");
        btnguardar.setEnabled(false);
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        txt_total.setDescripcion("Total compra");
        txt_total.setEnabled(false);
        txt_total.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N

        labelMetric12.setBackground(new java.awt.Color(0, 0, 0));
        labelMetric12.setForeground(new java.awt.Color(0, 0, 0));
        labelMetric12.setText("Gs.");
        labelMetric12.setColorDeSombra(new java.awt.Color(255, 255, 255));
        labelMetric12.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N

        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        labelMetric13.setBackground(new java.awt.Color(0, 0, 0));
        labelMetric13.setForeground(new java.awt.Color(0, 0, 0));
        labelMetric13.setText("Total Compra:");
        labelMetric13.setColorDeSombra(new java.awt.Color(255, 255, 255));
        labelMetric13.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelMetric1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(383, 383, 383))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(labelMetric12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelMetric13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)))))
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(labelMetric1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelMetric13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMetric12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cod_provKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cod_provKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //aqui definimos una matriz de tipo JTextField[] y el numero de columnas
            JTextField[] tfParam = new JTextField[2];
            //se le asigna donde va a mostrar el valor de cada columna
            tfParam[0] = this.cod_prov;
            tfParam[1] = this.proveedor;
            //instanciamos nuestra clase VentanaBuscar que se encuentra en el paquete clases
            //creamos la consulta con select de acuerdo a lo que queremos mostrar
            //en nuestra VentanaBuscar
            VentanaBuscar busmar = new VentanaBuscar("select cod_proveedor, razon_social from proveedor where razon_social like ",
                    new String[]{"CODIGO", "Proveedor",}, 2, tfParam);
            //colocamos un titulo a nuestra VentanaBuscar con el comando setTitle
            busmar.setTitle("Buscar Proveedor");
            //en esta linea hacemos que sea visible nuestra VentanaBuscar
            //con el comando setVisible
            busmar.setVisible(true);
            //en esta linea nos posicionamos y habilitamos sobre el combo deposito
            cod_prov.setEnabled(false);
            nro_fac.setEnabled(true);
            nro_fac.requestFocus();

        }
    }//GEN-LAST:event_cod_provKeyPressed

    private void userKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userKeyPressed

    }//GEN-LAST:event_userKeyPressed

    private void txt_cod_producKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cod_producKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //aqui definimos una matriz de tipo JTextField[] y el numero de columnas
            JTextField[] tfParam = new JTextField[3];
            //se le asigna donde va a mostrar el valor de cada columna
            tfParam[0] = this.txt_cod_produc;
            tfParam[1] = this.txt_produc;
            tfParam[2] = this.txt_precio;
            //instanciamos nuestra clase VentanaBuscar que se encuentra en el paquete clases
            //creamos la consulta con select de acuerdo a lo que queremos mostrar
            //en nuestra VentanaBuscar
            VentanaBuscar busmar = new VentanaBuscar("select a.cod_producto, a.p_descrip, a.precio\n"
                    + "from producto a, u_medida b, tipo_producto c\n"
                    + "where a.cod_tipo_prod=c.cod_tipo_prod and a.id_u_medida=b.id_u_medida and a.p_descrip like ",
                    new String[]{"CODIGO", "Producto", "Precio",}, 3, tfParam);
            //colocamos un titulo a nuestra VentanaBuscar con el comando setTitle
            busmar.setTitle("Buscar Producto");
            //en esta linea hacemos que sea visible nuestra VentanaBuscar
            //con el comando setVisible
            busmar.setVisible(true);
            //en esta linea nos posicionamos y habilitamos sobre el combo deposito
            txt_cod_produc.setEnabled(false);
            txt_precio.setEnabled(true);
            txt_cantidad.setEnabled(true);
            txt_cantidad.requestFocus();
        }
    }//GEN-LAST:event_txt_cod_producKeyPressed

    private void cargartabla() {
        cursor = (DefaultTableModel) this.grilla.getModel();
        int variable = 0;

        for (int c = 0; c < cursor.getRowCount(); c++) {
            if (cursor.getValueAt(c, 0).equals(txt_cod_produc.getText())) {//pregunta si el item agregado es igual al que existe en la taba
                r = Integer.parseInt(txt_cantidad.getText())//suma la cantidad nueva con la ya existente de la tabla
                        + Integer.parseInt(String.valueOf(cursor.getValueAt(c, 3)));
                r1 = r * Integer.parseInt(txt_precio.getText());//se multiplica la cantidad total * el precio unit
                cursor.setValueAt(r, c, 3);//nuevo valor de cantidad
                //cursor.setValueAt(r1, c, 4);

                variable = 1;
            }
        }

        if (variable == 1) {
            txt_cod_produc.setText("");
            txt_produc.setText("");
            txt_precio.setText("");
            txt_cantidad.setText("");
            txt_cod_produc.requestFocus();
            txt_cod_produc.setEnabled(true);
            txt_cantidad.setEnabled(false);

        } else {

            int subtotal = 0;
            subtotal = Integer.parseInt(txt_cantidad.getText()) * Integer.parseInt(txt_precio.getText());
            total = total + subtotal;
            txt_total.setText(formateador.format(total));

            String campo[] = new String[]{txt_cod_produc.getText(), txt_produc.getText(),
                txt_precio.getText(), txt_cantidad.getText()};
            cursor.addRow(campo);

        }

        txt_cod_produc.setText("");
        txt_produc.setText("");
        txt_precio.setText("");
        txt_cantidad.setText("");
        txt_cod_produc.requestFocus();
        txt_cod_produc.setEnabled(true);
        txt_cantidad.setEnabled(false);

    }

    private void limpiargrilla() {//limpiar la tabla
        while (cursor.getRowCount() > 0) {
            cursor.removeRow(0);
        }
    }
    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        accion = 1;
        generar_codigo();
        deshab_botones(1);
        cod_prov.setEnabled(rootPaneCheckingEnabled);
        cod_prov.requestFocus(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnagregarActionPerformed

    private void nro_facActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nro_facActionPerformed
        nro_fac.setEnabled(false);
        cbo_deposito.setEnabled(true);
        cbo_deposito.requestFocus();
    }//GEN-LAST:event_nro_facActionPerformed

    private void cod_provActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cod_provActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cod_provActionPerformed

    private void txt_cod_producActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cod_producActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cod_producActionPerformed

    private void txt_cantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cantidadKeyPressed

        if (evt.getKeyCode() == 10) {
            this.cargartabla();
            btnguardar.setEnabled(true);
        }

    }//GEN-LAST:event_txt_cantidadKeyPressed


    private void cbo_depositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_depositoActionPerformed

    }//GEN-LAST:event_cbo_depositoActionPerformed

    private void cbo_depositoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbo_depositoKeyPressed
        txt_cod_produc.setEnabled(true);
        txt_cod_produc.requestFocus();
        cbo_deposito.setEnabled(false);
    }//GEN-LAST:event_cbo_depositoKeyPressed

    private void cbo_depositoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbo_depositoMouseClicked
        txt_cod_produc.setEnabled(true);
        txt_cod_produc.requestFocus();
    }//GEN-LAST:event_cbo_depositoMouseClicked

    private void txt_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantidadActionPerformed

    }//GEN-LAST:event_txt_cantidadActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        limpiar_txt();
        deshab_botones(2);
        limpiar_grilla();
        desab_txt();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        int m = JOptionPane.showConfirmDialog(this, "Deseas Salir", "Atención", JOptionPane.YES_NO_OPTION);
        if (m == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_btnsalirActionPerformed

    private void txt_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_precioActionPerformed
        txt_cantidad.requestFocus();
    }//GEN-LAST:event_txt_precioActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        grabar();
        limpiar_txt();
        deshab_botones(2);
        limpiar_grilla();
        desab_txt();
    }//GEN-LAST:event_btnguardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new formularios.Producto(null, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Compra dialog = new Compra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void llenar_combo_depo(String orden) {
        try {
            rs = con.Listar("select concat(cod_deposito,'-',descrip) "
                    + "as dep from deposito order by cod_deposito=" + orden + " desc");
            if (rs.isBeforeFirst()) {
                while (rs.next()) {
                    cbo_deposito.addItem(rs.getString("dep"));
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Compra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void generar_codigo() {
        try {
            String sql = "select coalesce(max(cod_compra),0)+1 as cod from compra";
            rs = con.Listar(sql);// Devolver en rs(variable), el resultado del primer registro
            rs.next();//devuelve todos los valores del resultado
            this.cod.setText(rs.getString("cod"));
        } catch (SQLException ex) {
            Logger.getLogger(Compra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void fecha() {
        try {
            rs = con.Listar("select to_char(current_date,'DD/MM/YYYY')AS fecha");
            rs.next();
            this.fecha.setText(rs.getString("fecha"));
        } catch (SQLException ex) {
            Logger.getLogger(Compra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void hora() {
        try {
            rs = con.Listar("select to_char(current_timestamp, 'HH12:MI:SS')AS hora");
            rs.next();
            this.hora.setText(rs.getString("hora"));
        } catch (SQLException ex) {
            Logger.getLogger(Compra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void deshab_botones(int a) {
        switch (a) {
            case 1:
                this.btnagregar.setEnabled(false);

                this.btncancelar.setEnabled(true);
                this.btnsalir.setEnabled(false);
                break;

            case 2:
                this.btnagregar.setEnabled(true);
                btnguardar.setEnabled(false);
                this.btncancelar.setEnabled(true);
                this.btnsalir.setEnabled(true);
                break;

        }
    }

    private void limpiar_txt() {
        txt_cod_produc.setText("");
        txt_produc.setText("");
        txt_precio.setText("");
        txt_cantidad.setText("");
        cod.setText("");
        cod_prov.setText("");
        proveedor.setText("");
        nro_fac.setText("");
        txt_total.setText("");

    }

    private void desab_txt() {
        txt_cod_produc.setEnabled(false);
        txt_produc.setEnabled(false);
        txt_precio.setEnabled(false);
        txt_cantidad.setEnabled(false);
        cod.setEnabled(false);
        cod_prov.setEnabled(false);
        proveedor.setEnabled(false);
        nro_fac.setEnabled(false);
        txt_total.setEnabled(false);

    }

    private void limpiar_grilla() {
        cursor = (DefaultTableModel) grilla.getModel();
        while (cursor.getRowCount() > 0) {// CONTAR LA CANTIDAD DE ELEMENTOS HASTA 0
            cursor.removeRow(0);
        }
    }

    private void grabar() {
        if (accion == 1) {
            String estado = "activo";
            //grabar cabecera de factura    
            String monto = this.txt_total.getText();
            String mon = monto.replace(".", "");
            con.insertar_datos("compra", "cod_compra,cod_proveedor,nro_factura,"
                    + "fecha,estado,cod_deposito,hora,total_compra", cod.getText() + ","
                    + cod_prov.getText() + ","
                    + nro_fac.getText() + ","
                    + "(select ('" + this.fecha.getText() + "')::date)," + "'estado'" + ","
                    + "(select split_part('" + cbo_deposito.getSelectedItem() + "','-',1)::integer),"
                    + "(select ('" + this.hora.getText() + "')::time),"+mon+"", 1);

            //grabar detalle
            for (int a = 0; a < grilla.getRowCount(); a++) {

                con.insertar_datos("detalle_compra", "cod_producto,cod_compra,cod_deposito,"
                        + "precio,cantidad",
                        grilla.getValueAt(a, 0) + ","
                        + cod.getText() + ","
                        + "(select split_part('" + cbo_deposito.getSelectedItem() + "','-',1)::integer),"
                        + grilla.getValueAt(a, 2) + ","
                        + grilla.getValueAt(a, 3) + "", 2);

            }

            for (int b = 0; b < grilla.getRowCount(); b++) {
                try {
                    rs = con.Listar("select *from stock where cod_producto=" + grilla.getValueAt(b, 0) + " and cod_deposito=" + "(select split_part('" + cbo_deposito.getSelectedItem() + "','-',1)::integer)");
                    boolean encontro = rs.next();
                    if (encontro == false) {
                        con.insertar_datos("stock", "cod_producto,cod_deposito,cantidad,cajas",
                                grilla.getValueAt(b, 0) + ","
                                + "(select split_part('" + cbo_deposito.getSelectedItem() + "','-',1)::integer),"
                                + grilla.getValueAt(b, 3) + ","
                                + grilla.getValueAt(b, 3) + "/12", 2);
                    } else {
                        String sql = "update stock set cantidad=cantidad +" + grilla.getValueAt(b, 3)
                                + ", cajas=cantidad/12 where cod_producto=" + grilla.getValueAt(b, 0) + " and cod_deposito="
                                + "(select split_part('" + cbo_deposito.getSelectedItem() + "','-',1)::integer)";
                       System.out.println(sql);
                        con.sentencia = con.conectar().createStatement();
                        con.sentencia.executeUpdate(sql);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Compra.class.getName()).log(Level.SEVERE, null, ex);
                }

            }   

        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox cbo_deposito;
    private org.edisoncor.gui.textField.TextFieldRectBackground cod;
    private org.edisoncor.gui.textField.TextFieldRectBackground cod_prov;
    private org.edisoncor.gui.textField.TextFieldRectBackground fecha;
    private javax.swing.JTable grilla;
    private org.edisoncor.gui.textField.TextFieldRectBackground hora;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private org.edisoncor.gui.label.LabelMetric labelMetric1;
    private org.edisoncor.gui.label.LabelMetric labelMetric10;
    private org.edisoncor.gui.label.LabelMetric labelMetric11;
    private org.edisoncor.gui.label.LabelMetric labelMetric12;
    private org.edisoncor.gui.label.LabelMetric labelMetric13;
    private org.edisoncor.gui.label.LabelMetric labelMetric2;
    private org.edisoncor.gui.label.LabelMetric labelMetric3;
    private org.edisoncor.gui.label.LabelMetric labelMetric4;
    private org.edisoncor.gui.label.LabelMetric labelMetric5;
    private org.edisoncor.gui.label.LabelMetric labelMetric6;
    private org.edisoncor.gui.label.LabelMetric labelMetric7;
    private org.edisoncor.gui.label.LabelMetric labelMetric8;
    private org.edisoncor.gui.label.LabelMetric labelMetric9;
    private org.edisoncor.gui.textField.TextFieldRectBackground nro_fac;
    private org.edisoncor.gui.textField.TextFieldRectBackground proveedor;
    private org.edisoncor.gui.textField.TextFieldRectBackground txt_cantidad;
    private org.edisoncor.gui.textField.TextFieldRectBackground txt_cod_produc;
    private org.edisoncor.gui.textField.TextFieldRectBackground txt_precio;
    private org.edisoncor.gui.textField.TextFieldRectBackground txt_produc;
    private org.edisoncor.gui.textField.TextFieldRectBackground txt_total;
    private org.edisoncor.gui.textField.TextFieldRectBackground user;
    // End of variables declaration//GEN-END:variables
}
