/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import prg.conex;

/**
 *
 * @author utic
 */
public class deposito extends javax.swing.JDialog {

    /**
     * Creates new form ciudad
     */
    conex con; //llamar al metodo conexión
    ResultSet rs; //llamar al metodo de resultados
    
    String operacion= "";//Variable para establecer las operaciones(Agregar,Modificar o Borrar)
    
    javax.swing.table.DefaultTableModel cursor; //crear un cursor que va a cargar la tabla
    
    public deposito(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(this); //centrar
        this.deshab_inicio();// llamar el metodo para desabilitar campos y botones.
       
       con = new conex(); //Instanciar la coenxion
       con.conectar(); //Utilizar el metodo para conectar
       cargar_grilla();
       buscar.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNice1 = new org.edisoncor.gui.panel.PanelNice();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        descrip = new org.edisoncor.gui.textField.TextFieldRectBackground();
        codigo = new org.edisoncor.gui.textField.TextFieldRectBackground();
        jScrollPane1 = new javax.swing.JScrollPane();
        grilla = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnagregar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnborrar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        buscar = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelNice1.setBackground(new java.awt.Color(209, 149, 94));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Depósito", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N
        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Ubuntu Condensed", 1, 15)); // NOI18N
        jLabel1.setText("Código:");

        jLabel2.setFont(new java.awt.Font("Ubuntu Condensed", 1, 15)); // NOI18N
        jLabel2.setText("Descripción:");

        descrip.setEnabled(false);
        descrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripActionPerformed(evt);
            }
        });
        descrip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                descripKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                descripKeyTyped(evt);
            }
        });

        codigo.setEnabled(false);
        codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoActionPerformed(evt);
            }
        });
        codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codigoKeyPressed(evt);
            }
        });

        grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion"
            }
        ));
        grilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grillaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(grilla);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DialogInput", 1, 14))); // NOI18N
        jPanel2.setOpaque(false);

        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo1.png"))); // NOI18N
        btnagregar.setText("Agregar");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.png"))); // NOI18N
        btnmodificar.setText("Modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Floppy2.png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnborrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar1.png"))); // NOI18N
        btnborrar.setText("Borrar");
        btnborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarActionPerformed(evt);
            }
        });

        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar1.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnguardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnmodificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnagregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnborrar, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnagregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(132, 132, 132)
                    .addComponent(btnborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(173, Short.MAX_VALUE)))
        );

        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir_press.png"))); // NOI18N
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        buscar.setBorder(javax.swing.BorderFactory.createTitledBorder("Bucar"));
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        btnbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnbuscarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel1))
                                    .addComponent(jLabel2))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(descrip, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnbuscar)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(32, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(descrip, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnbuscar))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))))
        );

        panelCurves1.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        panelNice1.add(panelCurves1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelNice1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelNice1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void descripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripActionPerformed
        this.descrip.setEnabled(false);
        btnguardar.setEnabled(true);
        btnguardar.requestFocus();//enviar el cursor en el boton
        
    }//GEN-LAST:event_descripActionPerformed

    private void codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoActionPerformed
    //        descrip.requestFocus();
                
              descrip.setEnabled(true);
              descrip.requestFocus();
              buscar_ciudad();
              
              if("borrar".equals(operacion)){
                  descrip.setEnabled(false);
                  
                    int m=JOptionPane.showConfirmDialog(this,"Confirmar acción","Eliminar",JOptionPane.YES_NO_OPTION);
            if(m==JOptionPane.YES_OPTION){
                this.guardar();
                this.limpiar_grilla();
           this.cargar_grilla();
           this.deshab_botones(2);
           this.deshab_inicio();
           this.limpiar_txt();   
                
            }
              }
//           this.guardar();
//           this.deshab_botones(2);
//           this.deshab_inicio();
//           this.limpiar_txt();   
         
    }//GEN-LAST:event_codigoActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        
 
        
      int mensaje= JOptionPane.showConfirmDialog(this, "¿Desea Salir?", "Atención", JOptionPane.YES_NO_OPTION);
      if(mensaje ==JOptionPane.YES_OPTION) {
         dispose(); //salir completamente del sistema 
    
      } 
      //dispose(); // cerrar ventana pero el sistema sigue ejecutandose
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        // TODO add your handling code here:
        this.operacion = "agregar";
        this.deshab_botones(1);
        this.generar_codigo();
        this.descrip.setEnabled(true);
        this.descrip.requestFocus();
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        this.deshab_botones(2);
        this.deshab_inicio();
        this.limpiar_txt();
        this.limpiar_grilla();
        this.cargar_grilla();
        this.deshab_inicio();
        this.limpiar_txt();   
    }//GEN-LAST:event_btncancelarActionPerformed

    private void descripKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descripKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER){ //cuando el evento del teclado fue enter
            if (descrip.getText().equals("")){ //getText leer el texto es igual a vacio
                JOptionPane.showMessageDialog(null, "NO DEBE DEJAR EL CAMPO VACIO");
                descrip.requestFocus();//situar el cursor en descrip
            }
        }
        
    }//GEN-LAST:event_descripKeyPressed

    private void descripKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descripKeyTyped
        // TODO add your handling code here:
        int k = evt.getKeyChar();//guardar en la variable k el evento del teclado
        if (k > 47 && k < 58){ //mientras el evento sea codigo aschi
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            getToolkit().beep(); //el sonido del error
            JOptionPane.showMessageDialog(null,"No puede ingresar Números");
            descrip.requestFocus();
        }
      
        
    }//GEN-LAST:event_descripKeyTyped

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        int mensaje = JOptionPane.showConfirmDialog(this,"Desea confirmar la acción", "Atención",JOptionPane.YES_NO_OPTION);
            if(mensaje == JOptionPane.YES_OPTION){
          validar_descripcion();
         
           this.limpiar_grilla();
           this.cargar_grilla();
           this.deshab_botones(2);
           this.deshab_inicio();
           this.limpiar_txt();   
        } 
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        this.operacion = "modificar";
        JOptionPane.showMessageDialog(this, "Ingrese el código de lo que deseas eliminar");
        this.codigo.setEnabled(true);
        codigo.requestFocus();
        
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void codigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_codigoKeyPressed

    private void btnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarActionPerformed
        // TODO add your handling code here:
        this.operacion = "borrar";
       JOptionPane.showMessageDialog(this, "Ingrese el código de lo que deseas eliminar");
          
            

            
         this.codigo.setEnabled(true);
         this.codigo.requestFocus();
        
   
    }//GEN-LAST:event_btnborrarActionPerformed

    private void grillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grillaMouseClicked
        this.verdatos();
    }//GEN-LAST:event_grillaMouseClicked

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        limpiar_grilla();
        this.buscar();
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
      this.btnbuscar.setEnabled(true);
      btnbuscar.requestFocus();
    }//GEN-LAST:event_buscarActionPerformed

    private void btnbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnbuscarKeyPressed
        limpiar_grilla();
        this.buscar();
    }//GEN-LAST:event_btnbuscarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                deposito dialog = new deposito(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private void deshab_inicio(){
        this.codigo.setEnabled(false);
        this.descrip.setEnabled(false);
        this.btnguardar.setEnabled(false);

    }
    
    private void deshab_botones(int a) {
        switch(a){
            case 1:
                this.btnagregar.setEnabled(false);
                this.btnmodificar.setEnabled(false);
                this.btnborrar.setEnabled(false);
              
                this.btnsalir.setEnabled(false);
                break;
                
            case 2:
                 this.btnagregar.setEnabled(true);
                this.btnmodificar.setEnabled(true);
                this.btnborrar.setEnabled(true);
               
                this.btnsalir.setEnabled(true);
                break;

        }
    }
    private void limpiar_txt(){
         this.descrip.setText("");
        this.codigo.setText("");
    }
    
    private void generar_codigo(){
        try {
            String sql = "select coalesce(max(cod_deposito),0)+1 as cod from deposito";
            rs = con.Listar(sql);// Devolver en rs(variable), el resultado del primer registro
            rs.next();//devuelve todos los valores del resultado
            this.codigo.setText(rs.getString("cod"));
        } catch (SQLException ex) {
            Logger.getLogger(deposito.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void guardar() {
         
        try {
            String sql="";
            if ("agregar".equals(operacion)){
                
                sql ="INSERT INTO deposito VALUES("+codigo.getText()+",'"+descrip.getText().toUpperCase()+"')";
              JOptionPane.showMessageDialog(null, "El registro " +descrip.getText()+ " fue agregado correctamente.");

                
                
            }
            if ("modificar".equals(operacion)){

                sql ="UPDATE deposito set descrip = '"+descrip.getText().toUpperCase()+"' where cod_deposito="+codigo.getText()+" ";
                System.out.print(sql);// visualizar lo que se está ejecutanto
                
              JOptionPane.showMessageDialog(null, "El registro de codigo nro " +codigo.getText()+ " fue modificado correctamente.");

            }
            if ("borrar".equals(operacion)){
                
                sql ="delete from deposito where cod_deposito= "+codigo.getText()+" ";
                System.out.print(sql);// visualizar lo que se está ejecutanto
                
               JOptionPane.showMessageDialog(null, "El registro " +codigo.getText()+ " fue elimnado correctamente.");
                
            }
            con.sentencia=con.conectar().createStatement();
            con.sentencia.executeUpdate(sql);
          // con.conectar().close();
        } catch (SQLException ex) {
            Logger.getLogger(deposito.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void cargar_grilla(){
        try {
            cursor = (DefaultTableModel) grilla.getModel(); //asignar el cursor a la grilla
            String sql = "select * from deposito order by cod_deposito"; //consulta para cargar tabla
            rs=con.Listar(sql); // guarda los resultados del select en rs
            
            String [] fila = new String [2]; // definir array para guardar todos los id y descrip de la consulta
            while(rs.next()){ // va  a cargar con los valores del resultado (rs) obtenido en la consulta
                fila[0]= rs.getString("cod_deposito"); // datos de la fila 0= id's
                fila[1]= rs.getString("descrip");//datos de la fila las descripciones
                cursor.addRow(fila); //cargar con el cursor los valores eh la tabla
            }
        } catch (SQLException ex) {
            Logger.getLogger(deposito.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void limpiar_grilla(){
        cursor = (DefaultTableModel) grilla.getModel();
        while(cursor.getRowCount()>0){// CONTAR LA CANTIDAD DE ELEMENTOS HASTA 0
            cursor.removeRow(0);
        }
    }
    
    private void buscar_ciudad(){
        try {
            String sql="select descrip as descripcion from deposito where cod_deposito="+codigo.getText();
            rs = con.Listar(sql);// Devolver en rs(variable), el resultado del primer registro
            rs.next();//devuelve todos los valores del resultado
            this.descrip.setText(rs.getString("descripcion"));
        } catch (SQLException ex) {
            Logger.getLogger(deposito.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void verdatos() {
        int fila = grilla.getSelectedRow();
        codigo.setText(grilla.getValueAt(fila, 0).toString());
        descrip.setText(grilla.getValueAt(fila, 1).toString());

    }
    
    private void buscar() {
        try {
            cursor = (DefaultTableModel) this.grilla.getModel();//asignacion del modelo de la tabla al cursor creado
            String sql = "select * from deposito where cod_deposito like '%"+buscar.getText().toUpperCase()+"%' order by cod_deposito";
            rs = con.Listar(sql);
            String[] fila1 = new String[2];//definimos la cantidad que poseera el array[]
            
            while (rs.next()) {
                fila1[0] = rs.getString("cod_deposito");
                fila1[1] = rs.getString("descrip");
                cursor.addRow(fila1);//agrega filas mientras que exista datos
            }
        } catch (SQLException ex) {
            Logger.getLogger(deposito.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void validar_descripcion() {
        try {
            rs = con.Listar("SELECT * FROM deposito WHERE descrip = '"
                    + this.descrip.getText().toUpperCase() + "'");
            boolean encontro = rs.next();
            if (encontro == true) {
                JOptionPane.showMessageDialog(null, "La descripcion de la ciudad   "
                        + descrip.getText() + "   ya se encuentra registrada");
               // this.habilitar(1);
            } else {
              guardar();
            }
        } catch (SQLException ex) {
            Logger.getLogger(deposito.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnborrar;
    private javax.swing.JToggleButton btnbuscar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JTextField buscar;
    private org.edisoncor.gui.textField.TextFieldRectBackground codigo;
    private org.edisoncor.gui.textField.TextFieldRectBackground descrip;
    private javax.swing.JTable grilla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    private org.edisoncor.gui.panel.PanelNice panelNice1;
    // End of variables declaration//GEN-END:variables
}
